"""Initial migration

Revision ID: adb8b0b86c43
Revises: 
Create Date: 2025-01-15 23:27:17.288324

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'adb8b0b86c43'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('creation_time', sa.DateTime(), nullable=True),
    sa.Column('cost', sa.Numeric(), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('cost', sa.Numeric(), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('task_products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('deployment_state', sa.String(length=1), nullable=True),
    sa.Column('type', sa.String(length=10), nullable=False),
    sa.Column('context_id', sa.String(length=255), nullable=False),
    sa.Column('instance_id', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task_products')
    op.drop_table('task')
    op.drop_table('product')
    # ### end Alembic commands ###
